services:
  api-gateway:
    build: ./api-gateway
    ports:
      - '4000:4000'
    depends_on:
      - clients
      - suppliers
      - billing
      - products
      - retentioncode
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

  auth:
    build: ./auth
    ports:
      - '3000:3000'
    environment:
      - DB_URI=mongodb://mongo:27017/authDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

  clients:
    build: ./clients
    ports:
      - '3005:3005'
    environment:
      - DB_URI=mongodb://mongo:27017/clientsDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

  products:
    build: ./products
    ports:
      - '3006:3006'
    environment:
      - DB_URI=mongodb://mongo:27017/productsDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

  retentioncode:
    build: ./retentioncode
    ports:
      - '3009:3009'
    environment:
      - DB_URI=mongodb://mongo:27017/retentioncodeDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

  suppliers:
    build: ./suppliers
    ports:
      - '3003:3003'
    environment:
      - DB_URI=mongodb://mongo:27017/suppliersDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - app-network

  billing:
    build: ./billing
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/facturacionDB
      - P12_PASSWORD=Enri2023
      - AMBIENTE=pruebas
      - EMISION=1
      - ESTAB=001
      - PTOEMI=108
      - FIRMADOR_HOST=firmador
    volumes:
      - ./xmls:/app/xmls # Compartir la carpeta de XMLs entre billing y firmador
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mongo
      - firmador
    networks:
      - app-network

  retentions:
    build: ./retentions
    ports:
      - '3008:3008'
    environment:
      - MONGO_URI=mongodb://mongo:27017/retencionDB
      - P12_PASSWORD=Enri2023
      - AMBIENTE=pruebas
      - EMISION=1
      - ESTAB=001
      - PTOEMI=107
      - FIRMADOR_HOST=firmador
    volumes:
      - ./xmls:/app/xmls # Compartir la carpeta de XMLs entre billing y firmador
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mongo
      - firmador
    networks:
      - app-network

  savebilling:
    build: ./savebilling
    ports:
      - '3011:3011'
    environment:
      - MONGO_URI=mongodb://mongo:27017/savebillingDB
      - AMBIENTE=produccion
    volumes:
      - ./xmls:/app/xmls # Compartir la carpeta de XMLs entre billing y firmador
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mongo
    networks:
      - app-network

  firmador:
    build: ./firmador
    container_name: firmador
    volumes:
      - ./xmls:/app/xmls # Compartir la carpeta de XMLs entre billing y firmador
    ports:
      - '8081:8081'
    environment:
      - CERTIFICADO_PATH=/app/firmador/Firma/certificado.p12
      - CLAVE_PATH=/app/firmador/Firma/clave.txt
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - TZ=America/Guayaquil
    command: >
      sh -c "apt-get update && apt-get install -y tzdata && ln -fs /usr/share/zoneinfo/America/Guayaquil /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && mongod --bind_ip_all"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
