version: '3.9'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - '4000:4000'
    depends_on:
      - clients
      - suppliers
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  clients:
    build: ./clients
    ports:
      - '3005:3005'
    environment:
      - DB_URI=mongodb://mongo:27017/clientsDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  suppliers:
    build: ./suppliers
    ports:
      - '3003:3003'
    environment:
      - DB_URI=mongodb://mongo:27017/suppliersDB
    depends_on:
      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  billing:
    build: ./billing
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/facturacionDB
      - P12_PASSWORD=HJWvWIzJXs71
      - AMBIENTE=pruebas
      - EMISION=1
      - ESTAB=001
      - PTOEMI=101
    volumes:
      - C:/Users/willi/OneDrive/Escritorio/account-system/billing/src/firmas:/app/firmas
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - mongo

  firmador:
    build: ./firmador # Ruta donde está el Dockerfile del firmador
    ports:
      - '8080:8080'
    volumes:
      - ./org:/app/org
      - ./Firma:/app/Firma
    environment:
      - CERT_PATH=/app/Firma/certificado.p12
      - CLAVE_PATH=/app/Firma/clave.txt
    depends_on:
      - billing

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - TZ=America/Guayaquil
    command: >
      sh -c " apt-get update && apt-get install -y tzdata && ln -fs /usr/share/zoneinfo/America/Guayaquil /etc/localtime && dpkg-reconfigure --frontend noninteractive tzdata && mongod --bind_ip_all "

volumes:
  mongo-data:
