version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - '4000:4000'
    depends_on:
      - clients
      - suppliers

  clients:
    build: ./clients
    ports:
      - '3005:3005'
    environment:
      - DB_URI=mongodb://mongo:27017/clientsDB
    depends_on:
      - mongo

  suppliers:
    build: ./suppliers
    ports:
      - '3003:3003'
    environment:
      - DB_URI=mongodb://mongo:27017/suppliersDB
    depends_on:
      - mongo
  facturacion:
    build: ./facturacion
    ports:
      - '3001:3001'
    environment:
      - MONGO_URI=mongodb://mongo:27017/facturacionDB
      - P12_PASSWORD=qweqweqwe
      - AMBIENTE=pruebas # o 'produccion'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
